### ISSUE TITLE
Add copy and copytree methods

### ISSUE THREAD

**Issue by jayqi** [drivendataorg/cloudpathlib#108]
We should have `copy` and `copytree` methods for copying from one cloud path to another, similar to how [shutil's functions](https://docs.python.org/3/library/shutil.html#shutil.copy) work.

**Comment by genziano** [comment]
Hello, I was building a library for the same purpose, and I discovered this very nice one. I would like to contribute; is it ok if I pick this one up?

**Comment by jayqi** [comment]
Yes! Thank you for your interest and the offer to contribute! Let us know if you have any questions.

**Comment by pjbull** [comment]
That @genziano, that would be awesome. Just as a heads up, I think we may need two code paths:

(1) that uses the `_move_file` method on the client, which does a copy without transiting through the machine using cloudpath lib. (e.g., here is the [implementaiton for S3](https://github.com/drivendataorg/cloudpathlib/blob/master/cloudpathlib/s3/s3client.py#L149-L164)). This is only guaranteed to work if the `client` on the `CloudPath` is the same client (since then the creds can access both buckets).

(2) that can work across cloud providers. This will likely need to do a download then upload and transit through the machine running cloudpathlib code.

**Comment by genziano** [comment]
Great, I will work on it! And thanks for the tips.

I have one initial question: to which object should the methods `copy` and `copytree` belong? Or should they be functions in a submodule that replicates the `shutil` API?

**Comment by pjbull** [comment]
IMO on `CloudPath` makes the most sense. Usage would look like. @jayqi did you have other thoughts?

```python
p1 = CloudPath("s3://b/file1.txt")

# copies the file from p1 to the passed path
p2 = p1.copy(CloudPath("s3://b/file2.txt"))

# str destination passes through to instantiation using the CloudPath factory on p1
p2 = p1.copy("s3://b/file2.txt")

# dir destination copies and keeps filename
p2 = p1.copy(CloudPath("s3://b/folder/"))

# copy on a dir raises error to use copytree is src is not a file
CloudPath("s3://b/folder/").copy("s3://b/folder2")

# copies the entire directory from folder1 to folder2
CloudPath("s3://b/folder/").copytree("s3://b/folder2")

```

**Comment by machielg** [comment]
would be nice to have this feature, is there a plan for releasing?

**Comment by pjbull** [comment]
This is being looked at in PR #142 now. @BenAsaf had mentioned he may be able to take a look at implementing in the near future.
