### ISSUE TITLE
No Contributing Guidelines for the Project

### ISSUE THREAD

**Issue by saurabhMayank** [drivendataorg/cloudpathlib#213]
Please add a  `CONTRIBUTING.md` file mentioning how to contribute to this project.

**Comment by ms1596** [comment]
Any movements in this issue ????

**Comment by aaossa** [comment]
I've seen that many projects consider issues, bug reports, code contributions and more, as contributions. Considering that, it would be nice to include issue templates and maybe FAQ or common issues pinned somewhere for users. In the other hand, for code contributors some critical parts are:

* Setting up an environment (using `venv`)
* Installing dev/test dependencies
* Running the test suite (`make test`)
* Running linters (`make lint`)

To go further, it would be nice to have:
* Pointers to issue/PR labels looking for contributors
* A PR template with a checklist

I think that the contributing section of the [psf/black docs](https://black.readthedocs.io/en/latest/contributing/index.html) can be a good reference since it already includes some of the described items.

**Comment by pjbull** [comment]
Added, thanks for the comments @saurabhMayank @ms1596 @aaossa!

https://github.com/drivendataorg/cloudpathlib/blob/master/CONTRIBUTING.md
