### ISSUE TITLE
Enable `S3Path.mkdir`

### ISSUE THREAD

**Issue by the-matt-morris** [drivendataorg/cloudpathlib#295]
Just found this library, and I really love it!

I do have a use case where I'm wanting to run `mkdir()` command, but noticed that `S3Path.mkdir()` states it is not possible to create empty s3 directory:

https://github.com/drivendataorg/cloudpathlib/blob/96759b0de615a0d2f434b90c23f57ee673a238fa/cloudpathlib/s3/s3path.py#L41-L43

The method signature from the abstractmethod may not be ideal for the s3 situation (would have to play around with this), but it is possible to create an empty directory in s3.  I was using the `boto3.S3Client.put_object` method in my use case, but the proposed solution in [this comment](https://github.com/drivendataorg/cloudpathlib/issues/51#issuecomment-1245469574) looks good.

The issue with the comment referenced above does mention this problem, but I'm opening a separate issue dedicated for the `S3Path.mkdir` here because that issue has a larger scope and I believe this could be implemented quickly.  Let me know if you think this is off base, and I can close this.  Thanks!

**Comment by xyXiangYu** [comment]
@the-matt-morris , this is also what I am looking for. Additionally, I would like to copy files from local directory to s3 bucket while keeping the local directory structure. When making a folder locally, we can use `path.mkdir(parents=True, exist_ok=True)`, it seems such feature is missing in S3Path.mkdir. Hope this issue can be solved soon.

**Comment by xyXiangYu** [comment]
A less intuitive solution i am using now is  `CloudPath(f"{aws_s3_bucket_string}/existing_folder/subfolder_to_be_created/").touch()`. Then a `subfolder_to_be_created` directory will be created within the `existing_folder` on the AWS s3 bucket. It would be ideal to use the mkdir() method directly since it is more intuitive.

**Comment by pjbull** [comment]
Thanks for the thoughts @xyXiangYu and @the-matt-morris.

I'm curious about what your use cases are. We could implement `mkdir`, and we're definitely open to doing so with demonstrated user need.

We've been a little wary to do so just because of the [complexities](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html) of how the [abstraction](https://aws.amazon.com/premiumsupport/knowledge-center/s3-prefix-nested-folders-difference/) of a folder relates to the [S3 native representations](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-prefixes.html). I think following what the Amazon console does is probably the write implementation, but different clients of S3 can do things in different ways (e.g., by explicitly setting metadata properties of the directory objects).

We've also found that we don't usually have a need to create empty folders in S3 in our own usage—folders created "on demand" when we have an object to write has been enough.

**Comment by pjbull** [comment]
Thanks, @the-matt-morris—I'm working on a few s3 specific things right now so may look a little deeper at this issue.

In the meantime, does something like the following code should work in your case (even if the directory does not exist on S3) or is there an issue?

```python
path = ...  # any `cloudpathlib.CloudPath` or `pathlib.Path` object

with path.open("w") as f:
    data_frame.to_parquet(f)

```

Looking at [the `to_parquet` docs](https://pandas.pydata.org/pandas-docs/version/1.1/reference/api/pandas.DataFrame.to_parquet.html), there may be some other integration problems. Are you using `parition_cols` (in which case the multiple files it creates is a problem) or the `fastparquet` engine (which appears to not support file-like objects)?

In these cases, I might try code like the following. (Because, even if `mkdir` works on S3, the multi-file writing still won't do the upload automatically so your code will need to look a lot like this anyway).

```python
import tempfile

from cloudpathlib import CloudPath

# temporary directory for storing 
write_dir = tempfile.TemporaryDirectory()

# write to local directory
data_frame.to_parquet(write_dir, partition_cols=['a', 'b'])

# upload local directory to cloud destination
CloudPath("s3://bucket/folder_name").upload_from(write_dir)

# delete local version
write_dir.cleanup()
```

**Comment by xyXiangYu** [comment]
my case, as explained before, is that  I would like  manipulate the folders on s3 bucket just as what I am doing on a normal linux machine.  Especially, I would like to copy some files while honoring the folder/subfolder structure to a s3 bucket.  for example  copy all the files within local_folder, e.g.  `/folder/subfolder/file1, /folder/subfolder/file2`, to s3_clouldpath_folder /parent_folder/ then it should have `s3_bucket/parent_folder/folder/subfolder/file1, file2`.   if the path/folder along the directories do not exist, then error pops up. Ideally, would like to use the ClouldPath folder/files just as use it on local machine.

**Comment by pjbull** [comment]
Consolidating to #51. I think we should support `mkdir` for cloud providers that support either real or "virtual" folders.

**Comment by the-matt-morris** [comment]
Thanks for the update.  Initially I thought the first suggestion looked promising and would remove the need for initializing an empty directory, though I wasn't able to get it to work:

```python
with s3_path.open("w") as f:
    df.to_parquet(f, **kwargs)
```

```
Traceback (most recent call last):
  File "pyarrow/_parquet.pyx", line 1714, in pyarrow._parquet.ParquetWriter.__cinit__
  File "/usr/local/lib/python3.9/site-packages/pyarrow/util.py", line 93, in _stringify_path
    raise TypeError("not a path-like object")
TypeError: not a path-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyarrow/io.pxi", line 1797, in pyarrow.lib.get_writer
  File "/usr/local/lib/python3.9/site-packages/pyarrow/util.py", line 93, in _stringify_path
    raise TypeError("not a path-like object")
TypeError: not a path-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 2835, in to_parquet
    return to_parquet(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 420, in to_parquet
    impl.write(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 195, in write
    self.api.parquet.write_table(
  File "/usr/local/lib/python3.9/site-packages/pyarrow/parquet/core.py", line 2964, in write_table
    with ParquetWriter(
  File "/usr/local/lib/python3.9/site-packages/pyarrow/parquet/core.py", line 966, in __init__
    self.writer = _parquet.ParquetWriter(
  File "pyarrow/_parquet.pyx", line 1716, in pyarrow._parquet.ParquetWriter.__cinit__
  File "pyarrow/io.pxi", line 1801, in pyarrow.lib.get_writer
  File "pyarrow/io.pxi", line 828, in pyarrow.lib.PythonFile.__cinit__
TypeError: binary file expected, got text file
```

If that did work, it seems like it would be much cleaner than what I'm doing in my use case already.  This is what I'm doing after making directory and using `pydantic.SecretStr` for holding secret values:

```python
df.to_parquet(
    str(s3_path),
    storage_options={
        "key": s3.aws_access_key_id._secret_value,
        "secret": s3.aws_secret_access_key._secret_value,
    },
)
```

probably a cleaner way than this...

I can appreciate some of the reasoning provided here, though I still do think an abstract `mkdir` method that isn't implemented is a little confusing.  Consolidating with the other issue makes sense, thanks for the conversation around this topic!

**Comment by pjbull** [comment]
@the-matt-morris Would you try opening in binary mode instead of testmode (i.e., pass `"wb"` instead of `"w"` for the mode) like this:

```python
with s3_path.open("wb") as f:
    df.to_parquet(f, **kwargs)
```

**Comment by the-matt-morris** [comment]
@pjbull , wow duh...thank you.  Yes that works.  I guess I no longer have a use case that requires a `mkdir` method.

**Comment by pjbull** [comment]
Haha, no worries. Thanks for the discussion here. I think in the end we do want to support creating virtual folders since these days there are at least semi-official ways to do it on the three main providers, watch #51 if you want updates on implementation.
