### ISSUE TITLE
Setting Local client as default for testing

### ISSUE THREAD

**Issue by Gilthans** [drivendataorg/cloudpathlib#309]
Hey there!
In my code, there is a path that is extracted from environment variables, and thus has to be stored as a string.
During testing, I want to patch in a cloud path. I tried doing the following:
```
client = LocalGSClient(local_storage_dir=temp_dir)
client.set_as_default_client()
```
I assumed that when the code would use `AnyPath('gs://bucket/dir')` it would go to my local client and all would be well, but instead it fails with `Anonymous credentials cannot be refreshed.`

After inspecting the code, I understood the issue: each class has its own default client, *including `LocalGSClient`*. When `AnyPath` encounters a `gs://` path, it uses `GSClient` which has a different default client.

I tried to solve this in several ways, including registering `LocalGSClient` as a `localgs://` path, but couldn't find a way to get
`AnyPath(<a string>)` to return a path with my client.

Is there a way I'm missing to solve this? Is this intentional?

**Comment by pjbull** [comment]
@Gilthans have you tried the methods in the testing documentation? 
https://cloudpathlib.drivendata.org/stable/testing_mocked_cloudpathlib/

We usually patch the implementation registry so dispatch goes to the local rather than the cloud version. I think that should work for your case, but maybe I am misunderstanding something.

The docs use pytest, but here's an example just with the vanilla standard lib `unittest.mock` (helpfully [patch.dict](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch.dict) can be used as a context manager like below or as a decorator for your test functions)

```python
from unittest.mock import patch

from cloudpathlib import AnyPath, implementation_registry
from cloudpathlib.local import local_gs_implementation

# patch implementation registry;
with patch.dict(implementation_registry, {'gs': local_gs_implementation}):
    print(type(AnyPath("gs://should_be_local/local.txt")))
#> <class 'cloudpathlib.local.implementations.gs.LocalGSPath'>
```

Does that work for your tests?

**Comment by Gilthans** [comment]
Interesting, I didn't notice that section. I'll try and report back

**Comment by pjbull** [comment]
@Gilthans I'm going to close this for now, since I believe the above method should work. Feel free to reopen if not!
