### ISSUE TITLE
exists(gs://bucket/) fails with StopIteration on an empty bucket 

### ISSUE THREAD

**Issue by indigoviolet** [drivendataorg/cloudpathlib#356]
See previously: #291 , where it seems to have been fixed for S3

```
from cloudpathlib import CloudPath
CloudPath("gs://empty-bucket/").exists() # replace bucket name
```

**Comment by pjbull** [comment]
Thanks for the issue, looks like the implementation doesn't work right for empty buckets since it uses iteration:
https://github.com/drivendataorg/cloudpathlib/blob/45ae4ee163c06ef2a2e5939ede29a84630a4e08e/cloudpathlib/gs/gsclient.py#L147-L156

We should just use the `.exists` method on the bucket instead:
https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.bucket.Bucket#google_cloud_storage_bucket_Bucket_exists

Happy to accept a PR for this if you have the chance.
