### ISSUE TITLE
Add lower bound to boto3 dependency to make resolution smoother

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cloudpathlib#392]
See this poetry issue for discussion: https://github.com/python-poetry/poetry/issues/8799#issuecomment-1858394394

Need to figure out what a reasonable minimum for `boto3` is first.

**Comment by jayqi** [comment]
From reading that thread, I'm not convinced that it makes sense for us to put a lower bound on boto3 or botocore. Someone might genuinely need an older version of boto3 or botocore, or someone has another dependency that might have a ceiling on boto3 or botocore, and this would be an artificial constraint that prevents resolution.

It seems like the underlying issue is that botocore way overdoes it on "continuous" releases—they've got 1,800+ versions available on PyPI—and this can cause degenerately inefficient behavior in Poetry's dependency resolver. 

Two things that feel like more appropriate solutions to me would be:

1. Poetry figures out how to have their dependency resolver handle this case, since botocore is a common dependency and this problem must show up a lot
2. botocore makes itself more resolver-friendly by [yanking](https://pypi.org/help/#yanked) a lot of their old releases. This means those versions are still available but get ignored by resolvers.

IMO, 2 is the most sensible solution since this is ultimately a problem botocore has caused. I recognize that I'm shifting responsibility here from us to other projects, but I don't think us artificially introducing a floor on boto3/botocore is a reasonable solution.

**Comment by pjbull** [comment]
Agreed on all points

> artificially introducing a floor on boto3/botocore is a reasonable solution.

I guess I wonder if, for example, there's a set of versions that are purely incompatible with the versions of Python we support so we could set a lower bound that's not an artificial floor, but is an actual compatibility floor.
