### ISSUE TITLE
file: bug

### ISSUE THREAD

**Issue by pprados** [drivendataorg/cloudpathlib#416]
In implementation_registry, the file: is not present.

`CloudPath("file:data/faq/faq.cs)`

generate

`{InvalidPrefixError}InvalidPrefixError("Path file:data/faq/faq.csv does not begin with a known prefix ['az://', 's3://', 'gs://'].")`

Not, I use a *relative* url.

**Comment by jayqi** [comment]
Hi @pprados,

`CloudPath` intentionally does not support the `file:` URI scheme because a users' filesystem is not a cloud storage service. You should instead use `AnyPath`, which will recognize `file:` and return a normal pathlib `Path` subclass.

```python
from cloudpathlib import AnyPath

AnyPath("file:data/faq/faq.cs")
#> PosixPath('data/faq/faq.cs')
```

<sup>Created at 2024-03-07 13:40:09 EST by [reprexlite](https://github.com/jayqi/reprexlite) v0.5.0</sup>
