### ISSUE TITLE
Typo in Cache Mode envvar

### ISSUE THREAD

**Issue by mynameisfiber** [drivendataorg/cloudpathlib#423]
The cache mode envvar is `CLOUPATHLIB_FILE_CACHE_MODE` while it should be `CLOUDPATHLIB_FILE_CACHE_MODE`.

This is consistent across the project, however is definitely unexpected from a user perspective.

**Comment by pjbull** [comment]
😆 that is annoying and unexpected!

We'd accept a fix that:
 (1) reads both for the time being, since some people may have copy-pasted.
 (2) emits a deprecation warning if the typo'd `CLOUPATHLIB_FILE_CACHE_MODE` is used
 (2) updates docs and everything else to the correct env var so people use that going forward

**Comment by mynameisfiber** [comment]
I'll send a PR in the coming days!

**Comment by jayqi** [comment]
Closed by #424 / #426. New issue #425 captures removal of the deprecated typoed environment variable.
