### ISSUE TITLE
CloudPath warning message 

### ISSUE THREAD

**Issue by Megscammell** [drivendataorg/cloudpathlib#452]
We're using Python 3.12 and have cloudpathlib v0.18.1 installed. However, when we import CloudPath from cloudpathlib, we get the following warning message:

_RuntimeWarning: As the c extension couldn't be imported, `google-crc32c` is using a pure python implementation that is significantly slower. If possible, please configure a c build environment and compile the extension_

google_crc32c is a dependency of google-cloud-storage which is a dependency of cloudpathlib. I think the warning occurs as google_crc32c is not yet compatible with Python 3.12. Do you know if there's a fix in place so that this is rectified in a future release?

**Comment by pjbull** [comment]
Here's the `google-crc32c` thread on 3.12 support (including some potential workarounds):
https://github.com/googleapis/python-crc32c/issues/178

Looks like it will be in the 1.6 release of that package, but they are migrating build systems (see [149](https://github.com/googleapis/python-crc32c/issues/149)). 

Closing here since there isn't anything for us to do about the issue. You should add your request to that thread.
