### ISSUE TITLE
Stricter S3 bucket name string validation?

### ISSUE THREAD

**Issue by TomNicholas** [drivendataorg/cloudpathlib#489]
I noticed that `S3Path` allows path strings that the [AWS docs](https://docs.aws.amazon.com/prescriptive-guidance/latest/defining-bucket-names-data-lakes/faq.html#q5) say are not allowed.

> ### Are there limitations on what I can include in my S3 bucket or path's name?
> 
> Only lowercase letters, numbers, dashes, and dots are allowed in S3 bucket names. Bucket names must be three to 63 characters in length, must begin and end with a number or letter, and cannot be in an IP address format. The names must also be globally unique.
>
> For S3 bucket paths, you can use uppercase letters, but we recommend that you only use lowercase letters. Paths can also include additional symbols, but we recommend that you only use underscores, dashes, slashes, and numbers.

However, I can create an `S3Path` object violating basically all of these limitations:

```python
In [1]: from cloudpathlib import S3Path

In [2]: S3Path('s3://BUCKET/file.txt')
Out[2]: S3Path('s3://BUCKET/file.txt')

In [3]: S3Path('s3://bucket_bad_chars/file.txt')
Out[3]: S3Path('s3://bucket_bad_chars/file.txt')

In [4]: S3Path('s3://bu/file.txt')
Out[4]: S3Path('s3://bu/file.txt')

In [5]: S3Path('s3://bucket-longer-than-63-chars-000000000000000000000000000000000000000000000000/file.txt')
Out[5]: S3Path('s3://bucket-longer-than-63-chars-000000000000000000000000000000000000000000000000/file.txt')

In [6]: S3Path('s3://12.123.137.53')
Out[6]: S3Path('s3://12.123.137.53')

In [7]: S3Path('s3://_bucket_/file.txt')
Out[7]: S3Path('s3://_bucket_/file.txt')
```

Shouldn't these raise a `ValueError` at construction time?

**Comment by TomNicholas** [comment]
Having said that it seems like `pathlib` also doesn't forbid paths with invalid characters:

```python
In [10]: from pathlib import PureWindowsPath

In [11]: PureWindowsPath('<')
Out[11]: PureWindowsPath('<')
```

(`<` should apparently be illegal on Windows https://stackoverflow.com/a/31976060/3154101)

**Comment by pjbull** [comment]
Yeah, closing this since it would be a departure from pathlib, and there a bunch of "S3 API" compatible services (e.g., R2, MinIO) that could potentially have different bucket rules (even if it looks like these two don't necessarily from a quick Google).

**Comment by TomNicholas** [comment]
I mean I really feel like this is kinda insane to never do this validation (and it would be totally reasonable for the validation to be os / cloud-service-dependent), but I agree that `cloudpathlib` behaviour should be consistent with `pathlib`, even if I think `pathlib` should behave differently than it currently does. 😞

**Comment by TomNicholas** [comment]
> "S3 API" compatible services (e.g., R2, MinIO) that could potentially have different bucket rules

Surely a different service should have a different `CloudPath` subclass anyway? i.e. `R2Path` and `MinIOPath`. And those could have different path validation checks if that service has different naming rules.

**Comment by pjbull** [comment]
> I mean I really feel like this is kinda insane to never do this validation

We have a different philosophy for this project for two reasons. First, enforcement of this kind of constraint should be the responsibility of either (1) the official SDK we use, or (2) the service backend itself. Pushing as much as possible to these layers lets us minimize the amount of code we write that is tightly coupled to implementation details that can change and incur maintenance burden.

Second, like with the Windows characters, doing this validation would mean you get an error only slightly sooner in the execution since (1) if the path stays virtual it doesn't matter, and (2) if the bucket doesn't exists (because it can't) you'll get an error anyway.

> Surely a different service should have a different CloudPath subclass anyway?

What we've heard from users is that treating them as just another S3 implementation where they set the endpoint explicitly works well. Having different classes confuses a configuration parameter (what service hosts S3 API endpoint) with an implementation parameter (where we would change the library used or need other custom code, etc.).

**Comment by TomNicholas** [comment]
Thank you very much for that explanation @pjbull! I'm not sure that changed my opinion, but those are certainly reasonable motivations for this project.

For context [my use case](https://github.com/zarr-developers/VirtualiZarr) involves validating and manipulating many local/cloud/http paths to scientific data whilst potentially never actually accessing what's at those paths. Instead we're collecting, validating, and caching (to disk) the paths so that a later reader application (on the data user side rather than the scientific data provider side) uses another library to actually read data from those paths.

With that, a related question is if 

> doing this validation would mean you get an error only slightly sooner in the execution

then why do you enforce that the botocore dependency is installed at `S3Path` import time rather than at the point the user actually tries to read/write from S3? Right now you don't really have a notion of a "`PureS3Path`" because the dependency import assumes that if you instantiate `S3Path` you are actually planning to access S3 later. (came up in https://github.com/zarr-developers/VirtualiZarr/pull/243#issuecomment-2504680112)

(Apologies if this is an uninteresting rabbit hole for you 😅 )

**Comment by pjbull** [comment]
No worries, always interested in how folks are using the package and what is most useful even if we can't reasonably accommodate every scenario.

> For context [my use case](https://github.com/zarr-developers/VirtualiZarr) involves validating and manipulating many local/cloud/http paths to scientific data whilst potentially never actually accessing what's at those paths

That's an interesting use case, thanks for sharing. Out of curiousity, it seems more valuable to actually check if the S3 path exists rather than just checking if it could theoretically exist according to naming rules. 

> then why do you enforce that the botocore dependency is installed at S3Path import time rather than at the point the user actually tries to read/write from S3? 

Two reasons: (1) the fix in this scenario is to change the environment by installing packages, which can't be dealt with during error handling so it is makes a big difference for users to get this error ASAP. It is a relatively common scenario for people forget to install the right SDK via extras. And, (2) we don't want to guarantee that we won't use other functionality from the SDKs (whether or not they communicate with the backend).

For the issue you linked, we'd usually just install the s3 dependencies as well.
